---
name: Labeler

"on":
  push:
    branches:
      - "main"
      - "master"
      - "development/*"
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labeler.yml'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.1.0

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3.1.1
